Create sparse_matrix_addition.c
TechOUs/Algorithms pull request #108
Opened 2020-10-02 10:44 UTC by kiransbaliga

a program that converts matix to sparse form,find its transpose and addition of the two matrices in sparse form.
*contributed by*
@kiransbaliga[https://github.com/kiransbaliga]

2020-10-02 10:58 UTC, GauravWalia19 requested changes
Please update the README with algorithm you are adding

2020-10-02 13:19 UTC, kiransbaliga commented
okay will do, I am new at github,
 so should I do pull request again?

On Fri 2 Oct, 2020, 4:28 PM Gaurav Walia, <notifications@github.com> wrote:

> *@GauravWalia19* requested changes on this pull request.
>
> Please update the README with algorithm you are adding
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TechOUs/Algorithms/pull/108#pullrequestreview-501041387>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOB57EO7WNUTFAQKAN6UYTSIWW6LANCNFSM4SBRMGEQ>
> .
>

2020-10-02 18:34 UTC, GauravWalia19 requested changes
Please remove the MATRIX headings in the README and add the algorithm link under MISC heading

2020-10-03 15:01 UTC, GauravWalia19 requested changes

2020-10-03 15:01 UTC, GauravWalia19 commented on README.md
> +* MATRIX
Remove this line

2020-10-03 15:06 UTC, kiransbaliga commented on README.md
> +* MATRIX
I have removed it please check it!!

2020-10-05 17:45 UTC, GauravWalia19 approved these changes

2020-10-05 17:46 UTC, merged