Fibonacci_XOR problem added
TechOUs/Algorithms pull request #128
Opened 2020-10-04 19:45 UTC by riyavaryani

2020-10-05 18:06 UTC, GauravWalia19 commented
@riyavaryani please raise a issue with the HacktoberFest20 template.

2020-10-05 18:24 UTC, GauravWalia19 commented on MISC/Fibonacci_xor/C++/fibonacci_xor.cpp
> +  int a,b,n;
Here please use good naming like

int firstNumber, secondNumber, n;

2020-10-05 18:25 UTC, GauravWalia19 requested changes
Please update the cpp file with the mentioned comments
And also update the README file

2020-10-05 19:12 UTC, riyavaryani commented
changes done

2020-10-10 04:22 UTC, GauravWalia19 approved these changes

2020-10-10 04:24 UTC, merged